# smarttradex_core/markers/marker_store.py

class MarkerStore:
    """
    Stores markers generated by the engine.
    """

    def __init__(self):
        self._markers = []

    def add(self, marker: dict):
        if marker:
            self._markers.append(marker)

    def get_all(self):
        return self._markers

    def clear(self):
        self._markers = []
