import requests
import time

# ============================================================
# SmartTradeX API Client
# GUI → FastAPI → Engine / Binance
# REAL DATA – PAPER TRADING (SAFE)
# ============================================================

BASE_URL = "http://127.0.0.1:8000"
REQUEST_TIMEOUT = 8


# ============================================================
# SAFE REQUEST HANDLER (AUTO-REFRESH FRIENDLY)
# ============================================================

def safe_get(endpoint, retries=2, delay=0.3):
    url = f"{BASE_URL}{endpoint}"

    for _ in range(retries):
        try:
            response = requests.get(url, timeout=REQUEST_TIMEOUT)
            response.raise_for_status()
            return response.json()
        except Exception:
            time.sleep(delay)

    return None


# ============================================================
# REAL BINANCE CANDLES (TIMEFRAME SUPPORT)
# ============================================================

def get_candles(interval="5m"):
    """
    Fetch REAL Binance OHLCV candles with selectable timeframe.

    Supported intervals:
    1m, 3m, 5m, 15m, 1h, 4h, 1d
    """
    return safe_get(f"/market/candles?interval={interval}")


# ============================================================
# REAL BINANCE LIVE PRICE (TICKER)
# ============================================================

def get_live_price(symbol="BTCUSDT"):
    """
    Fetch REAL live price from Binance ticker.
    Used for live price overlay on chart.
    """
    url = "https://api.binance.com/api/v3/ticker/price"
    params = {"symbol": symbol}

    response = requests.get(url, params=params, timeout=5)
    response.raise_for_status()

    return float(response.json()["price"])


# ============================================================
# STRATEGY MARKERS (PAPER TRADING)
# ============================================================

def get_markers():
    """
    Fetch BUY / SELL / PREDICTION markers
    generated by paper trading engine.
    """
    return safe_get("/markers") or []


# ============================================================
# PAPER TRADES
# ============================================================

def get_trades():
    """
    Fetch paper trades executed using REAL prices.
    """
    return safe_get("/trades") or []


def get_positions():
    """
    Placeholder (future use).
    """
    return []


# ============================================================
# ENGINE STATE (NO MARKET DATA HERE)
# ============================================================

def get_state():
    """
    Fetch engine running / stopped state.
    """
    return safe_get("/state") or {}


# ============================================================
# ENGINE CONTROLS
# ============================================================

def start_engine():
    response = requests.post(
        f"{BASE_URL}/engine/start",
        timeout=REQUEST_TIMEOUT
    )
    response.raise_for_status()
    return response.json()


def stop_engine():
    response = requests.post(
        f"{BASE_URL}/engine/stop",
        timeout=REQUEST_TIMEOUT
    )
    response.raise_for_status()
    return response.json()


def reset_engine():
    """
    Paper trading reset (safe stub).
    """
    return {"status": "ok"}
